### ISSUE TITLE
CallRemoteAssistMinimal and CallRemoteAssistFromYourHoloLensApp don't work

### ISSUE THREAD

**Issue by IcyCheetah358** [microsoft/AppConsult-Samples-MixedReality#4]
The CallRemoteAssistMinimal when run with Unity 2017.2.1p2 gives an error on RS4 Hololens for:" Failed to get spatial controller - touch pad.... errorcode 0x00000". The fix to that error from internet is to use Unity version 2017.4. On Unity version 2017.4 nothing happens when the sphere is double-tapped.

The other  CallRemoteAssistFromYourHoloLensApp does not compile to VC project. It shows several errors on both Unity versions 2017.2 and 2017.4.

**Comment by sbovo** [comment]
Hello, thanks for the feedback. I check this.

**Comment by sbovo** [comment]
Hello, so I gave a try. Here is what I did:
- Downloaded the zip (or you can clone the repo of course)
- Opened the CallRemoteAssistMinimal folder with Unity (you can take the 2017.X version you want)
- Went to Build settings and switched to UWP + HoloLens + Unity C# project
- In the player settings, I verified .NET 4.6, .NET backend
- So I compiled
- I opened the resulting C# Solution, switched to x86, Device with the HoloLens plugged and start the debugging. This way you can put a breakpoint in the Start Method. You will hit the breakpoint

Please note that you have to install the "Remote Assist" app on the HoloLens

**Comment by IcyCheetah358** [comment]
Yes I have it (RemoteAssist) installed. Just the example does not launch it, no matter how much I air-tap the sphere. I can launch it (Remote Assist) from menu and make calls with it.

**Comment by sbovo** [comment]
Ok, I tested using Windows 1809 on HoloLens and several Unity version.
Can you try the following very quick workaround?

```
        await Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
        {
            // Work done on the UI thread
            LaunchURI(uri).ConfigureAwait(false).GetAwaiter().GetResult();
        });
```

instead of 

`await LaunchURI(uri);`

I updated the source code of the repo with this code.
Sebastien.

**Comment by IcyCheetah358** [comment]
OK, tested it now again, with Unity 2017.4.15f1 (same as master now). This time with the zip-downloading instead of git clone. Interestingly I got Error 0x80010135: Path too long in decompressing the zip. So I made a shorter-path to be able to decompress it. This might explain some strange build-failures I got earlier in Visual Studio when trying to deploy to device:

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'I:\repos\17_4\Windows-ppConsult-Samples-MixedReality\RemoteAssistSamples\CallRemoteAssistMinimal\App1\CreateObjects\UnityEngine.Networking.dll'.
2>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2>     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2>     at Unity.LoadModulesStep.Execute()
2>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
2>     at Unity.Operation.Execute()
2>     at Unity.Program.Main(String[] args)`

With the shorter file-path the build-error was also gone (did not get it when I built to pre-1809 HoloLens for some unknown reason).

When air-tapped, there is a window to select either Skype of Remote Assist to open the link. Choosing Remote Assist works most of the time (record so far is that it works three times in a row). Many times times after selecting Remote Assist to open the link, just the HoloLens spatial mapping menu animation kicks in and Remote Assist is nowhere to been seen. The Unity app window is selectable but the Remote Assist has apparently crashed. 

However the main issue that nothing happens when air-tapping the sphere appears to be solved.

**Comment by sbovo** [comment]
Thanks for your feedback!

**Comment by DeenuMaurya** [comment]
Hello I have some query I have HoloLens 1 and I build Hololens remote assist but I click the "Remote Assist video call" button then open another application and I can't see unity Object please help me Thanks

**Comment by eswarborra** [comment]
Hi Team 
   With your project we are able to call but we are unable to go back to our application.
Please help me out.
