### ISSUE TITLE
CreateObjects Demo

### ISSUE THREAD

**Issue by predictcare** [microsoft/AppConsult-Samples-MixedReality#5]
Hi, looking at the tutorial, there are big black holes on running the application, tapping and seeing the block falls.

Can you check please ?

Thanks

**Comment by sbovo** [comment]
Hello, have you used the sample code from GitHub or the instructions in https://blogs.msdn.microsoft.com/appconsult/2018/06/14/create-a-windows-mixed-reality-app-from-0-a-simple-example/?
What is the problem? Is it because you do not see the "ground floor"?

Thanks,
Sebastien.

**Comment by predictcare** [comment]
Hi Seb, we just discussed that on the MSDN forum. It's okay now (you have to use application on real Hololens), you can surely close.

Thanks, again.
