### ISSUE TITLE
Test on emulator

### ISSUE THREAD

**Issue by HosseinArabbeigi** [microsoft/AppConsult-Samples-MixedReality#7]
Hi there!

Thanks for amazing sample project
Can i test it on emulator? or hololens device is required?

**Comment by Abdul-Mukit** [comment]
@HosseinArabbeigi Hi. Did you have any luck testing it on the emulator?

**Comment by Abdul-Mukit** [comment]
Nevermind, I was able to run it using the emulator. It was pretty easy. Just followed the steps of 
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100
and
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101e

**Comment by Abdul-Mukit** [comment]
I was able to run the app on the emulator but I got the following error when the code called InitializeCameraCapture inside ScanEngine class.
"No capture device available..."
I am guessing we can't access cameras in an emulator. If anyone knows for sure please reply.

**Comment by cheles** [comment]
@Abdul-Mukit HL2 Emulator doesn't support camera .
